In [28]:
# python
# 출처: https://ebbnflow.tistory.com/135

In [2]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense, LSTM

In [27]:
x = array([[1,2,3], [2,3,4], [3,4,5], [4,5,6], [5,6,7], [6,7,8], [7,8,9], [8,9,10], [9,10,11], [10,11,12], [20,30,40], [30,40,50], [40,50,60]])
y = array([4,5,6,7,8,9,10,11,12,13,50,60,70])

print(x)
print('\n')
print(y)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [20 30 40]
 [30 40 50]
 [40 50 60]]


[ 4  5  6  7  8  9 10 11 12 13 50 60 70]


In [15]:
print('x.shape', x.shape)
print('y.shape', y.shape)

x.shape (13, 3)
y.shape (13,)


In [17]:
x = x.reshape(x.shape[0], x.shape[1], 1)
print('x.shape', x.shape)

x.shape (13, 3, 1)


In [18]:
model = Sequential()
model.add(LSTM(10, activation = 'relu', input_shape = (3,1), return_sequences=True)) # 이전의 기록을 다음으로 넘기기 위해서 return_sequences=True로 받음
model.add(LSTM(10, activation = 'relu', return_sequences=True))
model.add(LSTM(10, activation = 'relu', return_sequences=True))
model.add(LSTM(10, activation = 'relu', return_sequences=True))
model.add(LSTM(10, activation = 'relu', return_sequences=True))
model.add(LSTM(10, activation = 'relu', return_sequences=True))
model.add(LSTM(10, activation = 'relu', return_sequences=True))
model.add(LSTM(10, activation = 'relu', return_sequences=True))
model.add(LSTM(3)) # 마지막 output 3개, return_sequences=False

model.add(Dense(5))
model.add(Dense(1))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 3, 10)             480       
_________________________________________________________________
lstm_1 (LSTM)                (None, 3, 10)             840       
_________________________________________________________________
lstm_2 (LSTM)                (None, 3, 10)             840       
_________________________________________________________________
lstm_3 (LSTM)                (None, 3, 10)             840       
_________________________________________________________________
lstm_4 (LSTM)                (None, 3, 10)             840       
_________________________________________________________________
lstm_5 (LSTM)                (None, 3, 10)             840       
_________________________________________________________________
lstm_6 (LSTM)                (None, 3, 10)             8

In [19]:
model.compile(optimizer='adam', loss='mse')

In [22]:
model.fit(x,y, epochs=1, batch_size=2, verbose=2)

print(x)

7/7 - 0s - loss: 904.0180
[[[ 1]
  [ 2]
  [ 3]]

 [[ 2]
  [ 3]
  [ 4]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 5]
  [ 6]
  [ 7]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 7]
  [ 8]
  [ 9]]

 [[ 8]
  [ 9]
  [10]]

 [[ 9]
  [10]
  [11]]

 [[10]
  [11]
  [12]]

 [[20]
  [30]
  [40]]

 [[30]
  [40]
  [50]]

 [[40]
  [50]
  [60]]]


In [24]:
x_input = array([25, 35, 45])
x_input = x_input.reshape(1,3,1)

y_hat = model.predict(x_input)
print(y_hat)

[[0.12050679]]
